#Eureka Server Configuration for DEV
spring:
  profiles:
    active: native
  application:
    name: config-service
server:
  port: 8166
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# Eureka Server Configuration for DEV
  instance:
    appName: config-service
    leaseRenewalIntervalInSeconds: 50
    leaseExpirationDurationInSeconds: 30
    # preferIpAddress: false    