server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    decoderName: alioss-file
  serviceUrl:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/