#Eureka Server Configuration for DEV
spring:
  application:
    name: order-service
server:
  port: 8085
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# Eureka Server Configuration for DEV
  instance:
    appName: order-service
    leaseRenewalIntervalInSeconds: 50
    leaseExpirationDurationInSeconds: 30
    # preferIpAddress: false