#Eureka Server Configuration for DEV
spring:
  application:
    name: order-service
security.user.name: admin
security.user.password: 123456
management.security.enabled: false
management.security.role: ADMIN
#server:
#  port: 8085
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.16.65.52:8761/eureka/
# Eureka Server Configuration for DEV
  instance:
    appName: order-service
    leaseRenewalIntervalInSeconds: 50
    leaseExpirationDurationInSeconds: 30
    # preferIpAddress: false