#Eureka Server Configuration for DEV
spring:
  application:
    name: producer-service
server:
  port: 8082
eureka:
  name: producer-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# Eureka Server Configuration for DEV
  instance:
    appName: producer-service
    leaseRenewalIntervalInSeconds: 50
    leaseExpirationDurationInSeconds: 30
    # preferIpAddress: false    